const selectors = {
  popup: '.popup',
  popupProfile: '.popup_data_profile',
  popupAvatar: '.popup popup_data_avatar',
  popupCard: '.popup_data_card',
  popupImage: '.popup_data_image',

  editButtonProfile: '.profile__edit-button',
  titleProfile: '.profile__title',
  subtitleProfile: '.profile__subtitle',
  addCardButton: '.profile__add-button',
  avatarProfile: '.profile__image',
  popupOpen: '.popup_opened',
  closePopupButton: '.popup__button-close',
  popupInput: '.popup__input',
  popupInputName: '.popup__input_data_name',
  popupInputJob: '.popup__input_data_job',
  popupContainer: '.popup__container',
  buttonSubmit: '.popup__button-save',
  buttonDisabled: '.popup__button-save_disabled',
  popupTextError: '.popup__error',
  popupFormCard: '.popup__form_data_card',
  closePopupCardButton: '.popup__button-close_data_card',
  popupCardInputName: '.popup__input_data_name-card',
  popupCardInputLink: '.popup__input_data_link',
  templateCard: '.template-card',
  card: '.card',
  cardsSpace: '.cards',
  likeButton: '.card__like',
  likeButtonActive: '.card__like_active',
  likeBtnActive: 'card__like_active',
  deleteButton: '.card__delete',
  imageCard: '.card__image',
  imageCaption: '.popup__caption',
  cardTitle: '.card__title',
  closePopupImagedButton: '.popup__button-close_data_image',
  formPopup: '.popup__form',
  imagePopup: '.popup__image',
  cardLikeCounter: '.card__like-counter',
  popupDeleteCard: '.popup_data_delete-card'
}

export { selectors };
